apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: lets-encrypt-prod
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: <email>
   privateKeySecretRef:
     name: lets-encrypt-prod
   http01: {}
