apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sample-selfsigned-cert
spec:
  commonName: sample.crswty.com
  secretName: sample-selfsigned-cert-tls
  issuerRef:
    name: selfsigned
